export const suburbArray = [
    { label: 'Advancetown' },
    { label: 'Arundel' },
    { label: 'Ashmore' },
    { label: 'Benowa' },
    { label: 'Biggera Waters' },
    { label: 'Bilinga' },
    { label: 'Broadbeach' },
    { label: 'Bundall' },
    { label: 'Burleigh Heads' },
    { label: 'Burleigh Waters' },
    { label: 'Carrara' },
    { label: 'Chevron Island' },
    { label: 'Clear Island Waters' },
    { label: 'Coolangatta' },
    { label: 'Coombabah' },
    { label: 'Coomera' },
    { label: 'Currumbin' },
    { label: 'Currumbin Waters' },
    { label: 'Currumbin Valley' },
    { label: 'Elanora' },
    { label: 'Gaven' },
    { label: 'Helensvale' },
    { label: 'Highland Park' },
    { label: 'Hollywell' },
    { label: 'Hope Island' },
    { label: 'Isle of Capri' },
    { label: 'Jacobs Well' },
    { label: 'Kirra' },
    { label: 'Labrador' },
    { label: 'Main Beach' },
    { label: 'Maudsland' },
    { label: 'Mermaid Beach' },
    { label: 'Mermaid Waters' },
    { label: 'Merrimac' },
    { label: 'Molendinar' },
    { label: 'Mudgeeraba' },
    { label: 'Nerang' },
    { label: 'Nobbys Beach' },
    { label: 'Ormeau' },
    { label: 'Oxenford' },
    { label: 'Pacific Pines' },
    { label: 'Palm Beach' },
    { label: 'Paradise Point' },
    { label: 'Parkwood' },
    { label: 'Pimpama' },
    { label: 'Reedy Creek' },
    { label: 'Robina' },
    { label: 'Runaway Bay' },
    { label: 'Sanctuary Cove' },
    { label: 'Southport' },
    { label: 'Surfers Paradise' },
    { label: 'Tallai' },
    { label: 'Tallebudgera' },
    { label: 'Tugun' },
    { label: 'Varsity Lakes' },
    { label: 'Worongary' },
    { label: 'Miami' },
    { label: 'Miami' },
    { label: 'Miami' },
    { label: 'Miami' },
]